[project]
name = "ambitus-ai-models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckduckgo-api-haystack>=0.1.15",
    "fastmcp>=2.5.0",
    "haystack-ai>=2.13.2",
    "requests>=2.32.3",
]
